create table user (
  id int unsigned primary key auto_increment not null,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email varchar(255) not null unique,
  hashed_password varchar(255) not null,
  subscription BOOLEAN DEFAULT 0,
  role VARCHAR(50) NOT NULL DEFAULT 'utilisateur'
);

create table movie (
  id int unsigned primary key auto_increment not null,
  title VARCHAR(255) not null,
  synopsis TEXT not null,
  release_year YEAR  not null,
  duration TIME not null,
  poster VARCHAR(255) NOT NULL,
  trailer VARCHAR(255) NOT NULL,
  casting TEXT NOT NULL,
  production TEXT NOT NULL,
  landscape_image VARCHAR(255) DEFAULT NULL,
  premium BOOLEAN DEFAULT TRUE
);

create table genre (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL
);

create table movie_genre (
movie_id INT NOT NULL,
genre_id INT NOT NULL
);

create table watchlist (
movie_id int not null,
user_id int not null
);

INSERT INTO movie (title, synopsis, release_year, duration, poster, trailer, casting, production, landscape_image, premium)
VALUES
  ("Matrix","Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l'un des pirates les plus recherchés du cyber-espace. A cheval entre deux mondes, Neo est assailli par d'étranges songes et des messages cryptés provenant d'un certain Morpheus. Celui-ci l'exhorte à aller au-delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées : qu'est-ce que la Matrice ? Nul ne le sait, et aucun homme n'est encore parvenu à en percer les defenses. Mais Morpheus est persuadé que Neo est l'Elu, le libérateur mythique de l'humanité annoncé selon la prophétie. Ensemble, ils se lancent dans une lutte sans retour contre la Matrice et ses terribles agents...", "1999", "02:15:00", "https://fr.web.img4.acsta.net/c_310_420/medias/04/34/49/043449_af.jpg", "https://www.youtube.com/embed/vKQi3bBA1y8?si=Zb-r20gcbg3UOmeu", "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving", "Lilly Wachowski et Lana Wachowski", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/icmmSD4vTTDKOq2vvdulafOGw93.jpg",true),
  ("Inception","Un voleur spécialisé dans l'extraction d'informations secrètes par le biais du partage de rêves se voit confier l'impossible mission d'implanter une idée dans l'esprit d'un dirigeant...", "2010", "2:28:00","https://images.affiches-et-posters.com//albums/3/4532/medium/4532-affiche-film-inception-cast.jpg", "https://www.youtube.com/embed/YoHD9XEInc0?si=nbjr1E5OGbsGsDua", "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy", "Warner Bros. Pictures, Legendary Pictures, Syncopy", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",true),
  ("The Godfather", "Le patriarche vieillissant d'une puissante famille mafieuse transfère le contrôle de son empire clandestin à son fils réticent, déclenchant une série de trahisons et de conflits familiaux...", "1972", "2:55:00", "https://i.ebayimg.com/images/g/kWQAAOSwArteJsIw/s-l1200.jpg", "https://www.youtube.com/embed/sY1S34973zA?si=l2h2vWUdvz3TZ5F8", "Marlon Brando, Al Pacino, James Caan", "Paramount Pictures", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",true),
  ("The Shawshank Redemption", "Condamné à la prison à vie, un banquier entretient une amitié inattendue qui l'aide à trouver la rédemption et l'espoir derrière les barreaux...", "1994", "2:22:00", "https://images.squarespace-cdn.com/content/v1/657716dc6cd59d329f8cc943/1702303456952-89SVMRXKDUZ65S4279HJ/TSRL+Poster.jpg","https://www.youtube.com/embed/6hB3S9bIaco?si=xy07USbFeNuvEPr6", "Tim Robbins, Morgan Freeman", "Castle Rock Entertainment", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",true),
  ("The Dark Knight", "Batman doit affronter le Joker, un criminel sadique qui transforme Gotham en un terrain de chaos, mettant à l'épreuve ses idéaux et sa détermination...", "2008", "2:32:00", "https://fr.web.img2.acsta.net/medias/nmedia/18/63/97/89/18949761.jpg", "https://www.youtube.com/embed/EXeTwQWrcwY?si=s60vVctEjaHgHsh0", "Christian Bale, Heath Ledger, Aaron Eckhart", "Warner Bros. Pictures", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg",true),
  ("Fight Club", "Un employé de bureau insatisfait et un vendeur de savon forment un club secret de combat, qui dégénère en une organisation anarchique aux conséquences imprévues...", "1999", "2:19:00", "https://fr.web.img6.acsta.net/r_1280_720/pictures/210/212/21021246_20130719135446815.jpg", "https://www.youtube.com/embed/SUXWAEX2jlg?si=qXHZlJiCQ9EqIPZI", "Brad Pitt, Edward Norton, Helena Bonham Carter", "20th Century Fox, Regency Enterprises", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",true),
  ("Nomadland", "Une femme qui a tout perdu se lance dans un voyage à travers l'Ouest américain, adoptant le mode de vie d'une nomade moderne...", "2020", "1:47:00", "https://www.wiztopic.com/file/fx648pt7qg-phpnxojjt", "https://www.youtube.com/embed/6sxCFZ8_d84?si=z8B-Vv05gecsCb5X", "Frances McDormand, David Strathairn", "Searchlight Pictures", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/563sRDK3rZS31TXCdTY4lfcwrNK.jpg",true),
  ("Dune", "Dans un futur lointain, la lutte pour le contrôle d'une planète riche en ressources mène à des conflits interstellaires et politiques...", "2021", "2:35:00", "https://m.media-amazon.com/images/I/71XlZvKMwoL.jpg", "https://www.youtube.com/embed/n9xhJrPXop4?si=huTlvfEkkoBFr1fm", "Timothée Chalamet, Rebecca Ferguson, Oscar Isaac", "Warner Bros. Pictures, Legendary Entertainment, Villeneuve Films", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",true),
  ("The Power of the Dog", "Dans le Montana des années 1920, un charismatique rancher cache des secrets sombres qui vont perturber l'équilibre d'une famille...", "2021", "2:06:00", "https://media.senscritique.com/media/000020786307/0/the_power_of_the_dog.jpg", "https://www.youtube.com/embed/UpRzGl792tk?si=uJderrYME2T7ubgh", "Benedict Cumberbatch, Kirsten Dunst, Jesse Plemons", "Fox Searchlight Pictures", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/p1eneBfZCGbbzicwksOhIaibUwk.jpg",true),
  ("Everything Everywhere All at Once", "Une femme ordinaire se retrouve plongée dans une aventure interdimensionnelle pour sauver le multivers, confrontée à d'innombrables versions d'elle-même...", "2022", "139", "https://media.senscritique.com/media/000021157918/0/everything_everywhere_all_at_once.png", "https://www.youtube.com/embed/wxN1T1uxQ2g?si=_Q7nMXeW-75rVtyF", "Michelle Yeoh, Ke Huy Quan, Stephanie Hsu", "A24", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg",true),
  ("Drive My Car", "Suite à la perte de sa femme, un acteur se lance dans un voyage introspectif en acceptant un rôle dans une production théâtrale singulière...", "2021", "2:59:00", "https://fr.web.img5.acsta.net/pictures/21/08/04/12/37/4421523.jpg", "https://www.youtube.com/embed/6BPKPb_RTwI?si=qk36kZ7RyEXtHK0k", "Hidetoshi Nishijima, Reika Kirishima", "ROK International", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/r6aqhlmJmu8Dv5E7QYEruaEXKYm.jpg",true),
  ("L'amour au présent", "Une histoire touchante qui explore les paradoxes de l'amour moderne dans un monde en perpétuel changement...", "2025", "1:45:00", "https://media.senscritique.com/media/000022450747/300/lamour_au_present.png", "https://www.youtube.com/embed/9yadSQmKU_s?si=NahpV2i8Gp1lV7uS", "Julien Dupont, Sophie Martin", "Cinema France", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/4t8IXJF4umwCfbdpeKLvlN3zkKp.jpg",true),
  ("Un ours dans le Jura", "Un ours solitaire traverse le Jura pour découvrir le sens de la vie et l'amitié inattendue...", "2025", "1:50:00", "https://media.senscritique.com/media/000022468759/300/un_ours_dans_le_jura.png", "https://www.youtube.com/embed/zfQfUoN6IwM?si=96nBJPrS9vBZ1VIK", "Marc Leblanc, Camille Roche", "Jura Films", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/s7xmwFJQj99lICSGQkr8sQ7G9IA.jpg",false),
  ("Bird", "Un voyage émouvant dans l'univers d'un oiseau légendaire, symbole de liberté...", "2025", "2:00:00", "https://media.senscritique.com/media/000022481993/300/bird.png", "https://www.youtube.com/embed/scMh3X6byns?si=G5PW6SVw8TXK3zQq", "Emma Thompson, Robert Redford", "Skyline Studios", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/wwtZN9fy6BaFguj6wGPV0ZtCLHD.jpg",true),
  ("Elevation", "Un thriller haletant qui emmène les spectateurs au sommet de la tension et du suspense...", "2025", "2:05:00", "https://media.senscritique.com/media/000022548839/300/elevation.jpg", "https://www.youtube.com/embed/kt0V2rpEouE?si=1h6uhOXbkyAeGikr", "Alice Durand, Maxime Leroy", "High Altitude Pictures", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/au3o84ub27qTZiMiEc9UYzN74V3.jpg",true),
  ("Wallace et Gromit- La Palme de la Vengeance", "Les célèbres inventeurs se retrouvent au cœur d'une aventure rocambolesque mêlant humour et suspense...", "2025", "1:40:00", "https://media.senscritique.com/media/000022468409/300/wallace_et_gromit_la_palme_de_la_vengeance.png", "https://www.youtube.com/embed/pUaJVSWPtZk?si=UdUDGXR4WmU4Y0uR", "Voix : Nicolas Durand, Claire Fournier", "Stop Motion Productions", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/XNVdWNgiAHu8y4BsJv5ndUHXxN.jpg",true),
  ("La Chambre d'à côté", "Une comédie dramatique où les secrets d'une chambre voisine bouleversent la vie de ses habitants...", "2025", "1:55:00", "https://media.senscritique.com/media/000022497713/300/la_chambre_d_a_cote.png", "https://www.youtube.com/embed/41YRoaUsf6U?si=oAs-aiIpF0be7RVq", "Isabelle Moreau, Jean-Paul Gaultier", "Ciné Lumière", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/9Xx0BCkxDsF47niAPsb8lQ0O9Qu.jpg",false),
  ("Criminal Squad Pantera", "Une unité d'élite se bat contre le crime dans une ville aussi féroce qu'une panthère...", "2025", "2:10:00", "https://media.senscritique.com/media/000022545552/300/criminal_squad_pantera.png", "https://www.youtube.com/embed/K-IUU8VVKvM?si=9DPhZjAFokdj6bsu", "Thomas Bernard, Lara Dupuis", "Action Movies Inc.", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/mKIxSo3p1QKlsdegcOwapcbiV74.jpg",true),
  ("Mémoires d'un escargot", "À la mort de son père, la vie heureuse et marginale de Grace Pudel, collectionneuse d'escargots et passionnée de lecture, vole en éclats. Arrachée à son frère jumeau Gilbert, elle atterrit dans une famille d'accueil à l'autre bout de l’Australie. Suspendue aux lettres de son frère, ignorée par ses tuteurs et harcelée par ses camarades de classe, Grace s’enfonce dans le désespoir. Jusqu’à la rencontre salvatrice avec Pinky, une octogénaire excentrique qui va lui apprendre à aimer la vie et à sortir de sa coquille…", "2025", "1:34:00", "https://media.senscritique.com/media/000022500290/300/memoires_dun_escargot.png", "https://www.youtube.com/embed/GHlI58s-23w?si=GFI76YxFltwakOqE", "Gilbert Pudel (voice): Kodi Smit-McPhee, Pinky (voice): Jacki Weaver, James The Magistrate (voice): Eric Bana, Percy (voix): Dominique Pinon, Ruth (voix): Magda Szubanski, Bill Clarke (voice): Nick Cave, Denise Floyd (voice): Adam Elliot, Additional (voice): Flynn Wandin, Additional (voice): Ruby Davis", "Wild Bunch Distribution", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/jl2YIADk391yc6Qjy9JhgCRkHJk.jpg",false),
  ("Spectateurs !", "Un regard acerbe sur la société moderne où les observateurs deviennent acteurs d'une réalité déconcertante...", "2025", "1:55:00", "https://media.senscritique.com/media/000022109324/300/spectateurs.png", "https://www.youtube.com/embed/k0Ds2Udv-7A?si=mMff3-c9Ggk6Hgy6", "Luc Durand, Elise Martin", "Reflet Productions", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/yWUR8OaIC9YG14TSPKPQIeLAThr.jpg",true),
  ("Wolf Man", "Une réinvention moderne du mythe du loup-garou, mêlant horreur et drame psychologique...", "2025", "2:00:00", "https://media.senscritique.com/media/000022567984/300/wolf_man.png", "https://www.youtube.com/embed/XVyodxcVUxo?si=DUXZxksefJPWrGDa", "Vincent Cassel, Marion Cotillard", "Dark Moon Studios", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/nNF4ZB0UDL4qAUjQfbYZDq3Ck7J.jpg",true),
  ("Babygirl", "Un portrait touchant d'une jeune femme confrontée aux défis de la vie et de l'identité...", "2025", "1:40:00", "https://media.senscritique.com/media/000022574299/300/babygirl.png", "https://www.youtube.com/embed/jaX7rlzeM44?si=HJB47XDl7pdhs_ZX", "Lola Dubois, Antoine Mercier", "HeartBeat Films", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/hctfNoMpQGfn3VXdBYb9p0P5bT5.jpg",true),
  ("Je suis toujours là", "Un drame introspectif sur la résilience et la persévérance face aux épreuves de la vie...", "2025", "1:50:00", "https://media.senscritique.com/media/000022526927/300/je_suis_toujours_la.jpg", "https://www.youtube.com/embed/65UDWfkJGdo?si=oBpANt68fvDwnEsp", "Claire Simon, Laurent Pascal", "Everlasting Pictures", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/j9uruwRe9qM8RnP758dF7ISB8Bj.jpg",true),
  ("In the Grey", "Un thriller mystérieux où la frontière entre bien et mal se dissout dans une zone grise...", "2025", "2:05:00", "https://www.ecranlarge.com/content/uploads/2024/11/in-the-grey-affiche-officielle-630x945.jpg", "https://www.youtube.com/embed/zBqavRXa-7M?si=RPewIAIdvs7ho_hB", "Eva Green, Michael Fassbender", "Grey Area Films", NULL,true),
  ("Back in Action", "Alors qu’ils ont démissionné depuis longtemps de la CIA pour fonder une famille, Emily et Matt sont rattrapés malgré eux par l’espionnage lorsque leur couverture est démasquée...", "2025", "2:15:00", "https://media.senscritique.com/media/000022469847/300/back_in_action.png", "https://www.youtube.com/embed/zXTBl_31SXY?si=TOxwI4lGvjh9sU0B", "Jamie Foxx, Cameron Diaz", "Seth Gordon", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/xZm5YUNY3PlYD1Q4k7X8zd2V4AK.jpg",true),
  ("Pinocchio Unstrung", "Une réinterprétation audacieuse du conte classique, où le bois prend vie dans une aventure inattendue...", "2025", "1:45:00", "https://media.senscritique.com/media/000022323112/300/pinocchio_unstrung.jpg", "https://www.youtube.com/embed/arQv2zWpgiY?si=ZSV9PTzy_OXlSc0R", "Ewan McGregor, Scarlett Johansson", "Fairy Tale Productions", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/hPHEfhOmcWAKtZUWOEsBTHoUxUV.jpg",true),
  ("Better Man", "Une quête de rédemption et de transformation dans un monde en quête de justice et d'égalité...", "2025", "1:55:00", "https://media.senscritique.com/media/000022599251/300/better_man.png", "https://www.youtube.com/embed/o7kB9SjkIIk?si=cOGv49vgUlBdNZ4R", "Chris Hemsworth, Emily Blunt", "Evolution Films", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/3QeuagbU1YARTkGrPS4dvYSQGZi.jpg",true),
  ("Jouer avec le feu", "Un drame palpitant où la passion met le feu aux relations et dévoile des secrets inavoués...", "2025", "2:00:00", "https://media.senscritique.com/media/000022511252/300/jouer_avec_le_feu.png", "https://www.youtube.com/embed/SjDGx7ASUbg?si=KdktFhE_u0a2HMUC", "Sophie Marceau, Vincent Cassel", "Firelight Productions", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/19ddJDRfQxiXJXRidiEiJKjV53g.jpg",true),
  ("Vol à haut risque", "L'US Marshals Madelyn Harris est chargée d'escorter Winston, criminel et informateur, qui va témoigner contre un parrain de la mafia. Pendant leur voyage en avion, elle se méfie rapidement du pilote, Daryl Booth, qui ne semble pas être l'homme qu'il prétend...", "2025", "1:50:00", "https://media.senscritique.com/media/000022582019/300/vol_a_haut_risque.jpg", "https://www.youtube.com/embed/VG6iWe_8SHc?si=LD-CHQ_BAOx_bEf5", "Mark Wahlberg, Michelle Dockery, Topher Grace, Leah Remini, Paul Ben-Victor", "Mel Gibson", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",true),
  ("Nightbitch", "Après la naissance de son fils, une ancienne artiste reste chez elle et commence à développer la peur de se transformer en chien...", "2025", "1:38:00", "https://media.senscritique.com/media/000022545859/300/nightbitch.png", "https://www.youtube.com/embed/KlhgQRGGHk0?si=Vx0Pd4RApXRja88k", "Amy Adams, Scoot McNairy", "Marielle Heller", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/2ICMZZVcwboF8Z9V7aaJY3CVh9w.jpg",true),
  ("Star Trek: Section 31", "L'impératrice Philippa Georgiou rejoint une division secrète de Starfleet chargée de protéger la Fédération des planètes unies....", "2025", "1:50:00", "https://media.senscritique.com/media/000022592051/300/star_trek_section_31.jpg", "https://www.youtube.com/embed/kYfXhCp2UVY?si=hid3UWUpd-p_ejRa", "Michelle Yeoh, Omari Hardwick, Sam Richardson, Robert Kazinsky, Kacey Rohl", "Olatunde Osunsanmi", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/3SOunz2Z0qcOVlrkYFj20HquziB.jpg",true),
  ("Un parfait inconnu", "New York, début des années 60. Au cœur de l’effervescente scène musicale et culturelle de l’époque, un énigmatique jeune homme de 19 ans arrive dans le West Village depuis son Minnesota natal, avec sa guitare et un talent hors normes qui changeront à jamais le cours de la musique américaine. Alors qu’il noue d’intimes relations durant son ascension vers la gloire, il finit par se sentir étouffé par le mouvement folk et, refusant d’être mis dans une case, fait un choix controversé qui aura des...", "2025", "2:21:00", "https://media.senscritique.com/media/000022600281/300/un_parfait_inconnu.png", "https://www.youtube.com/embed/BPSw48CJamE?si=RiztQaCprpe_B5Ll", "Thimothée Chalamet, Bob Dylan, Edward Norton, Elle Fanning, Monica Barbaro, Boyd Holbrook", "James Mangold", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/r8YfVJu9OAzWbTAuuc86CIs1DYN.jpg",true),
  ("Companion", "Après avoir été invitée à un week-end dans la propriété au bord du lac de son nouvel amoureux, Iris découvre un terrible secret...", "2025", "1:37:00", "https://media.senscritique.com/media/000022544367/300/companion.jpg", "https://www.youtube.com/embed/7K6B4R9Ce0M?si=Ra8g4YMujOp0poXv", "Sophie Thatcher, Jack Quaid, Rupert Friend, Lukas Gage, Harvey Guillen, Marc Menchaca", "Greg Kwedar ", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/sc1abgWNXc29wSBaerrjGBih06l.jpg",false),
  ("Sing Sing", "Incarcéré à la prison de Sing Sing pour un crime qu’il n’a pas commis, Divine G se consacre corps et âme à l’atelier théâtre réservé aux détenus. À la surprise générale, l’un des caïds du pénitencier, Divine Eye se présente aux auditions...", "2025", "1:45:00", "https://media.senscritique.com/media/000022339180/300/sing_sing.png", "https://www.youtube.com/embed/2zjXCo-Nzt4?si=nK6IFc27rKxcLWRr", "Colman Domingo, Clarence Maclin, Sean Dino Johnson, Paul Raci, Sean San Jose, Miguel Valentin", "Redemption Studios", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/CZyMhVVpraYDptLpYXxXjgAuCH.jpg",true),
  ("God Save the Tuche", "Les Tuche mènent à nouveau une vie paisible à Bouzolles. Mais lorsque le petit-fils de Jeff et Cathy est sélectionné pour un stage de football à Londres, c’est l’occasion rêvée pour toute la famille d’aller découvrir l’Angleterre et de rencontrer la famille royale. Entre chocs culturels et maladresses, les Tuche se retrouvent plongés au cœur de la royauté anglaise, qui n’est pas prête d’oublier leur séjour!", "2025", "1:33:00", "https://media.senscritique.com/media/000022525173/300/god_save_the_tuche.png", "https://www.youtube.com/embed/K3aUaFbrd8g?si=jNFcXs_NupHiXlnC", " Jean-Paul Rouve, Isabelle Nanty, Claire Nadeau, Sarah Stern, Pierre Lottin, Theo Fernandez", "Jean-Paul Rouve", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/5C0WYWcdCfAQ4FU8yLCK4vAVk04.jpg",true),
  ("Presence", "Une famille emménage dans une nouvelle maison, hantée par une mystérieuse présence....", "2025", "1:25:00", "https://media.senscritique.com/media/000022592413/300/presence.png", "https://www.youtube.com/embed/4OBKT5yMTU0?si=5qz-IKN7ASVrmbx7", "Lucy Liu, Julia Fox, Chris Sullivan, Lucas Papaelias", "Steven Soderbergh", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/kpWusrV8GePdx42GLJjZ7RJhkfz.jpg",true),
  ("Paddington au Pérou", "Alors que Paddington rend visite à sa tante Lucy bien-aimée, qui réside désormais à la Maison des ours retraités au Pérou, la famille Brown et notre ours préféré plongent dans un voyage inattendu et plein de mystères, à travers la forêt amazonienne et jusqu'aux sommets des montagnes du Machu Picchu...", "2025", "1:43:00", "https://media.senscritique.com/media/000022635036/300/paddington_au_perou.png", "https://www.youtube.com/embed/Fp-1L1KOIk8?si=eKv4sdvt6GYj8ojO", "Ben Whishaw, Guillaume Gallienne, Hugh Bonneville, Emily Mortimer, Olivia Colman, Antonio Banderas", "Antoine Chevrollier", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/hfTyu2VPBqLRPo2DauW8q7bh9bm.jpg",true),
  ("La Pampa", "Willy et Jojo, deux ados inséparables, passent leur temps à chasser l’ennui dans un petit village au cœur de la France. Ils se sont fait une promesse : ils partiront bientôt pour la ville. Mais Jojo cache un secret. Et quand tout le village le découvre, les rêves et les familles des deux amis volent en éclat...", "2025", "1:44:00", "https://media.senscritique.com/media/000022602859/300/la_pampa.png", "https://www.youtube.com/embed/jZCpZAGCsoY?si=FBa1fUbdFVEI-aCD", "Sayyid El Alami, Amaury Foucher, Damien Bonnard, Florence Janas, Victor Artus Solaro (Artus), Léonie Dahan-Lamort", "Pablo Larraín", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/83HuU4KGMIbxL58l0Q3ADoLUHlt.jpg",true),
  ("Maria", "La vie de la plus grande chanteuse d’opéra du monde, Maria Callas, lors de ses derniers jours, en 1977, à Paris...", "2025", "2:04:00", "https://media.senscritique.com/media/000022484202/300/maria.png", "https://www.youtube.com/embed/1z0kHDNA4bU?si=7Wvp8h1emd1XLlzO", "Angelina Jolie, Pierfrancesco Favino, Alba Rohrwacher, Haluk Bilginer, Kodi Smit-McPhee, Stephen Ashfield", "Pablo Larraín", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/9iw4a6AQkxUO3EuRn59Vgrqf0zO.jpg",true),
  ("The Order - la confrérie de l'ombre", "Terry Husk, un agent chevronné du FBI, découvre un complot terroriste à l'intérieur du pays visant à renverser le gouvernement fédéral....", "2025", "1:54:00", "https://media.senscritique.com/media/000022635006/300/the_order_la_confrerie_de_l_ombre.png", "https://www.youtube.com/embed/_muGqDpJRQM?si=OZzgzke76P3KThdx", "Jude Law, Nicholas Hoult, Tye Sheridan, Jurnee Smollett, Odessa Young, Alison Oliver", "Justin Kurzel", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/aMbKYfaexixvsBZKc5whYO7yibR.jpg",true),
  ("The Brutalist", "L'histoire, sur près de trente ans, d'un architecte juif né en Hongrie, László Toth. Revenu d'un camp de concentration, il émigre avec sa femme, Erzsébet, après la fin de la Seconde Guerre mondiale aux États-Unis pour connaître son rêve américain...", "2025", "3:35:00", "https://media.senscritique.com/media/000022647875/300/the_brutalist.png", "https://www.youtube.com/embed/oFGs3-R1NyU?si=9iYT7MugFNtjSQca", "Adrien Brody, Felicity Jones, Guy Pearce, Joe Alwyn, Raffey Cassidy, Stacy Martin", "Brady Corbet", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/iKXXPYBWQ0B6BMRHAFbg3wKafWb.jpg",true),
  ("Les Damnés", "Hiver 1862. Pendant la guerre de Sécession, l’armée des Etats-Unis envoie à l’Ouest une compagnie de volontaires pour effectuer une patrouille dans des régions inexplorées. Alors que leur mission change de cap, ils questionnent le sens de leur engagement...", "2025", "1:28:00", "https://media.senscritique.com/media/000022544327/300/les_damnes.jpg", "https://www.youtube.com/embed/GCjP6gj9oeA?si=tuJVdGWRetdrrfXZ", "Cuyler Ballenger, Jeremiah Knupp, René W. Solomon, Noah Carlson, Timothy Carlson", "Roberto Minervini", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/gLJA6ZvM67EaEqen4bnF1xcnX4U.jpg",true),
  ("Captain America: Brave New World", "Peu après avoir fait la connaissance du nouveau président des Etats-Unis Thaddeus Ross, Sam Wilson se retrouve plongé au cœur d'un gigantesque incident international. Dans une lutte acharnée contre la montre, il se retrouve contraint de découvrir la raison de cet infâme complot avant que le véritable cerveau de l’opération ne mette bientôt le monde entier à feu et à sang...", "2025", "1:58:00", "https://media.senscritique.com/media/000022442264/300/captain_america_brave_new_world.png", "https://www.youtube.com/embed/PFU4wlAg7l0?si=TAcoYkyqZbgQxlDy", "Anthony Mackie, Harrison Ford, Danny Ramirez, Shira Haas, Tim Blake Nelson, Carl Lumbly", "Marvel Studios", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/qfAfE5auxsuxhxPpnETRAyTP5ff.jpg",true),
  ("Bridget Jones - Folle de lui", "Bridget Jones a cinquante-deux ans et deux enfants. Après le décès de Mark Darcy, avec qui elle a vécu dix ans de bonheur, elle est à nouveau en quête de l'homme idéal. Mais ce n'est pas si facile de se remettre sur le marché du célibat. Les mésaventures de Bridget n'ont rien perdu de leur piquant...", "2025", "2:05:00", "https://media.senscritique.com/media/000022514268/300/bridget_jones_folle_de_lui.png", "https://www.youtube.com/embed/8VIvXqW9_z4?si=8NtFgwJb0uHjtSpc", "Renée Zellweger, Colin Firth, Chiwetel Ejiofor, Leo Woodall, Hugh Grant, Emma Thompson", "Mickael Morris", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/zwSDvbnN51JqU1ULzPnEc22DkqV.jpg",true),
  ("Dis-moi juste que tu m'aimes", "Julien et Marie forment une famille heureuse et un couple solide, jusqu’au jour où Anaëlle, l’ex de Julien, reprend contact avec lui. Aveuglée par la jalousie, Marie entame alors, par dépit, une liaison Avec Thomas, son nouveau patron. Elle se retrouve vite embarquée dans une spirale dangereuse qui va mettre en péril bien plus que son mariage...", "2025", "1:51:00", "https://media.senscritique.com/media/000022560980/300/dis_moi_juste_que_tu_maimes.png", "https://www.youtube.com/embed/TvQFpb8aR_g?si=VfVozlZP9Cb9jZFZ", "Omar Sy, Élodie Bouchez, José Garcia, Vanessa Paradis, Jennifer Decker, Marie Ayissi", "Anne Le Ny", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/4dwfUlKtpame7tYR2mG3XQ0IHTH.jpg",true),
  ("Mercato", "Mercato nous plonge dans les coulisses du football d’aujourd’hui, industrie planétaire où les intérêts se chiffrent en milliards. Driss, agent de joueurs, a sept jours pour sauver sa peau avant la fin du mercato...", "2025", "1:59:00", "https://media.senscritique.com/media/000022592994/300/mercato.jpg", "https://www.youtube.com/embed/zW7gri3s1_g?si=ViArz3lrC5aUgd1C", "Jamel Debbouze, Monia Chokri, Milo Machado Graner, Hakim Jemili, Vincent Rottiers, Stéphane Bak", "Tristan Séguéla", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/2uEmC6WvlxL1H4RRFS567l3HoVP.jpg",true),
  ("L'attachement", "Sandra, quinquagénaire farouchement indépendante, partage soudainement et malgré elle l’intimité de son voisin de palier et de ses deux enfants. Contre toute attente, elle s’attache peu à peu à cette famille d’adoption....", "2025", "1:46:00", "https://media.senscritique.com/media/000022584014/300/l_attachement.jpg", "https://www.youtube.com/embed/jafK7yg0whg?si=4M2suYN0GzVjPNSa", "Valéria Bruni-Tedeschi, Pio Marmaï, Vimala Pons, Raphaël Quenard, César Botti, Catherine Mouchet", "Carine Tardieu", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/o9ELbiuZoDYYuBiQrJUkaZnfDqh.jpg",true),
  ("The Monkey", "Lorsque Bill et Hal, des jumeaux, trouvent dans le grenier un vieux jouet ayant appartenu à leur père, une série de morts atroces commence à se produire autour d'eux...", "2025", "1:38:00", "https://media.senscritique.com/media/000022466997/300/the_monkey.png", "https://www.youtube.com/embed/bYcBFKwupwY?si=Ezo1h6j7satIpjJn", "Theo James, Tatiana Maslany, Christian Convery, Colin O'Brien, Elijah Wood, Rohan Campbell", "Oz Perkins", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/6dC7ULfiutxwEAs7LjWHL2Tc7Zv.jpg",true),
  ("Peter Pan's Neverland Nightmare", "Adaptation horrifique de l'oeuvre de James Matthew Barrie...", "2025", "1:30:00", "https://media.senscritique.com/media/000022513281/300/peter_pan_s_neverland_nightmare.jpg", "https://www.youtube.com/embed/OYbxAYK8hoQ?si=Qm6aFyE5hXq3oPQB", "Charity Kase, Martin Portlock, Kit Green, Megan Placito, Olumide Olorunfemi, Philip Philmar", "Scott Chambers", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/nhx0ttmAS2w8e6hyIcKoNvgHoix.jpg",true),
  ("In the Lost Land", "Une reine cherche désespérément à concrétiser son amour. Elle engage alors une puissante sorcière nommée Gray Alys et l’envoie dans le désert fantomatique des Lost Lands, où Alys et son guide, le vagabond Boyce, doivent surpasser l’Homme et le démon...", "2025", "1:41:00", "https://media.senscritique.com/media/000022586849/300/in_the_lost_lands.jpg", "https://www.youtube.com/embed/hnPsOnw9-JU?si=zoJYaksqEYZ_fuTo", "Milla Jovovich, Dave Bautista, Arly Jover, Amara Okereke, Fraser James, Simon Lööf", "Paul W. S. Anderson", "https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/eOKpbUpd178x9Z2grd3vC74kkkU.jpg",true),
  ("Love Forever", "Un couple de Stockholm prévoit de se marier sur la splendide île de Gotland, mais des traditions imposées par la famille transforment leur célébration en un véritable désastre.", "2025", "1:36:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/e2yAyz0PR43aIxnGjv9HJryHBys.jpg", "https://www.youtube.com/watch?v=vszqLmBreN8", "Matilda Källström, Charlie Gustafsson, Kjell Bergqvist, Anja Lundqvist, Claes Malmberg", "Staffan Lindberg", NULL,true),
  ("La Dolce Villa", "Lorsque sa fille décide d'acheter une villa toscane délabrée, Eric, décidé à l'en dissuader, fonce en Italie. Il y découvre la beauté, une femme charmante et une nouvelle raison d'être.", "2025", "1:39:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/sEma5RN8aZ5Yu2Dkefyn5ULdlc1.jpg", "https://www.youtube.com/watch?v=NnEL3H0tl38", "Scott Foley, Violante Placido, Maia Reficco, Giuseppe Futia, Simone Luglio", "Mark Waters", NULL,true),
  ("Copenhague A Love Story", "Autumn, somewhere in Copenhagen: a pair of students, Emil and Victoria, can’t make their relationship work but can’t quite break up either. Philippe, who has just lost his job as a professor in a film school, followed by his apartment, can’t cope with the way his affair with a young literature student ended and now he’s crashing with some of his old students, including Emil. Naturally, he soon meets Victoria.", "2016", "1:40:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hpPIhxYjD8R3D7CwjcNJSSpaoCB.jpg", "https://www.youtube.com/watch?v=JlDLa2M1TG8", "Vic Carmen Sonne, Charlotte Uldall Baatrup, Emil Falke, Rudi Køhnke", "Philippe Lesage", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/njPGnuZe72Pi8t2uuKQUthWpy5h.jpg",true),
  ("The Wedding Banquet", "Pour faire plaisir à ses parents qui ne comprennent pas son célibat, un homosexuel dans le placard organise un mariage de convenance.", "2025", "1:42:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rO0MshHlXeuvUC0St8I7sfBaxRb.jpg", "https://www.youtube.com/watch?v=l61gmu9olZY", "Bowen Yang, Lily Gladstone, Kelly Marie Tran, Han Gi-chan", "Andrew Ahn", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/nvPjx2htKCIuDjCOV5H8ls3Du3e.jpg",true),
  ("À Contre-Sens Londres", "Noah, 18 ans, quitte l'Amérique pour s'installer à Londres avec sa mère qui vient de tomber amoureuse de William, un riche homme d'affaires britannique. Noah rencontre le fils de William, le rebelle Nick, et découvre qu'il existe entre eux une attirance indéniable. Noah passe l'été à s'adapter à sa nouvelle vie, mais son lourd passé va la rattraper au cœur de cette première idylle.", "2025", "1:59:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/y9ii1qorIELEshaxaLuF2MlyRv.jpg", "https://youtu.be/QFMWmFWUz1g", "Asha Banks, Matthew Broome, Eve Macklin, Ray Fearon", "Dani Girdwood", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/1OPhCM6zN4PiQ7PEWzlU3eg3xgO.jpg",true),
  ("Dracula A love Tale", "Après la mort de sa femme, un prince du XVe siècle renonce à Dieu et devient un vampire. Des siècles plus tard, dans le Londres du XIXe siècle, il voit une femme ressemblant à sa défunte épouse et la poursuit.", "2025", "1:58:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cRmYDUUesIhIeyJ1i00ib2iBeW.jpg", "https://www.youtube.com/watch?v=3Jg52APNfDY", "Caleb Landry Jones, Christoph Waltz, Zoë Bleu Sidel, Matilda De Angelis", "Keanu Reeves Concept", NULL,true),
  ("The Life List", "La mère d'Alex Rose l'encourage à compléter sa liste des choses à faire dans sa vie qu'elle a écrit enfant.", "2025", "2:30:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/m9NOJlDyKaXUUcIGyzAIMg9TzqD.jpg", "https://youtu.be/nldAfgJrBr8", "Sofia Carson, Kyle Allen, Sebastian de Souza, Connie Britton", "Adam Brooks", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/wnwv827EI2aGbGvDYv0PegUuz6D.jpg",true),
  ("Mickey 17", "Mickey 17 est un individu envoyé coloniser une planète gelée. A chaque fois qu'il meurt, ses souvenirs sont implantés dans un nouveau corps et sa mission reprend. Après être mort à six reprises, Mickey 17 commence à comprendre le but réel de sa mission.", "2025", "2:17:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/pEUdoUwezH3TheOC86bVKq241S0.jpg", "https://www.youtube.com/embed/-N11JtxUgak?si=E_Wh4Cz8S-7hSv3Z", "Robert Pattinson, Naomi Ackie, Steven Yeun", "Bong Joon-ho", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/hNA73rnG4PjSwgojaC2gbO1f8Rt.jpg",true),
  ("Gladiator 2", "Des années après avoir assisté à la mort du héros vénéré Maximus aux mains de son oncle, Lucius est forcé d'entrer dans le Colisée lorsque son pays est conquis par les empereurs tyranniques qui gouvernent désormais Rome d'une main de fer. La rage au cœur et l'avenir de l'Empire en jeu, Lucius doit se tourner vers son passé pour trouver la force et l'honneur de rendre la gloire de Rome à son peuple.", "2024", "2:27:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/7R1EXkBAKunoG0UhZToFrnlStcp.jpg", "https://www.youtube.com/embed/vEZjRSm5R3Y?si=FuneEi7EPOliZD4t", "Paul Mescal, Denzel Washington, Pedro Pascal, Connie Nielsen", "Ridley Scott", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/8mjYwWT50GkRrrRdyHzJorfEfcl.jpg",true),
  ("Dans l'ombre de Marlow", "Dans un désert où rien n'est ce qu'il semble être, Marlow cherche désespérément une boîte qui réalise les rêves. Mais alors qu’elle approche du but, une révélation bouleversante l’attend.", "2025", "1:20:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/3fYi5YpnIWftnhkmoHIvFPYDzHw.jpg", "https://www.youtube.com/embed/_MJxDwb9xKI?si=Wl9HCVD6XldvWtj0", "Richard Darbois, Armelle Deutsch, Thierry Desroses", "Aurélien HARZOUNE", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/iLNzFROgaqkqJ3vFMHqqGz1xc1K.jpg",true),
  ("Transformers: Le Commencement", "Les origines d'Optimus Prime et de Megatron, autrefois amis proches comme des frères, avant de devenir des ennemis jurés, façonnant ainsi à jamais le destin de Cybertron.", "2024", "1:44:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6PVLEv0WvXyIbp3RvGC5j3X5dAz.jpg", "https://www.youtube.com/embed/RwPAfxLt7H8?si=_gWSChB_j3Nj5kIY", "Chris Hemsworth, Brian Tyree Henry, Scarlett Johansson, Keegan-Michael Key, Jon Hamm", "Josh Cooley", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/hfznKmvhbOUB0W3GpW8HXIUoKXi.jpg",true),
  ("Copiapó", "Alexis Righetti et quatre de ses coéquipiers sont partis pendant un mois en autonomie complète dans la cordillère des Andes, afin de tenter d’emmener leur VTT le plus haut possible sur la planète. À plus de 6 000 mètres, les conditions météorologiques sont extrêmes, ils n'avaient ni assistance, ni oxygène… Une aventure folle aux paysages extraordinaires, faite de descentes vertigineuses et de l’ascension de certains des plus beaux sommets du monde.", "2025", "1:48:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/kHdJuzi86F5BkraSesrIfcTCQA1.jpg", "https://www.youtube.com/embed/0D_QPHujbuU?si=npy49YkQkSpFbR_q", "Alexis Righetti", "Alexis Righetti", NULL,true),
  ("Fast & Furious X", "Après bien des missions et contre toute attente, Dom Toretto et sa famille ont su déjouer, devancer, surpasser et distancer tous les adversaires qui ont croisé leur route. Ils sont aujourd’hui face à leur ennemi le plus terrifiant et le plus intime : émergeant des brumes du passé, ce revenant assoiffé de vengeance est bien déterminé à décimer la famille en réduisant à néant tout ce à quoi, et surtout à qui Dom ait jamais tenu.", "2023", "2:21:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/v1467wvoQIXlVY5MtAqt3PUtOdH.jpg", "https://www.youtube.com/embed/fAfs4JkeN78?si=ePNo7VJzIjOFyU38", "Vin Diesel, Michelle Rodriguez, Tyrese Gibson, Ludacris", "Louis Leterrier", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",true),
  ("Vice-versa 2", "Riley, adolescente depuis peu, au moment où le Quartier Cérébral doit être démoli pour faire place à un événement totalement inattendu : de nouvelles Émotions ! Joie, Tristesse, Colère, Peur et Dégoût, qui ont longtemps su contrôler les choses avec succès, ne savent pas comment réagir à l'arrivée d'Anxiété. Et il semblerait qu'elle ne soit pas seule. Elle est venue accompagnée d'Embarras, Envie et Ennui.", "2024", "1:37:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/9Jic8z9NEeCEmSJFgFHZF1lWMFo.jpg", "https://www.youtube.com/embed/DU_28YYtuQE?si=0101Ukx2BgckIWFK", "Amy Poehler, Maya Hawke, Kensington Tallman, Liza Lapira", "Kelsey Mann", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",true),
  ("Wicked", "Elphaba, une jeune femme incomprise à cause de sa peau verte inhabituelle, doit encore découvrir son véritable pouvoir. Glinda, une jeune femme populaire, dorée par le privilège et l'ambition, doit encore découvrir son véritable cœur. Les deux se rencontrent en tant qu'étudiantes à l'Université de Shiz dans le fantastique Pays d'Oz et forgent une amitié improbable, mais profonde.", "2024", "2:40:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/kQkgPhj6sCuoMWzPKWQVOWUXzib.jpg", "https://www.youtube.com/embed/x6A83rXWrE8?si=HS9BhJ_df8LzDY-2", "Cynthia Erivo, Ariana Grande, Jeff Goldblum, Michelle Yeoh, Jonathan Bailey", "Jon M. Chu", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",true),
  ("Stitch Head", "Suit Stitch Head, une petite créature éveillée par un professeur fou dans un château pour protéger les autres créations du professeur ainsi que les habitants de Grubbers Nubbin.", "2025", "2:06:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qwhscpTQAGrpit1ARQvvrlijp8h.jpg", "https://www.youtube.com/embed/P0HhH_XVpPk?si=EwhMianD3EUJT1r0", "Asa Butterfield, Joel Fry, Alison Steadman, Rob Brydon", "Steve Hudson", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/hNdD8w6OGgISCGBER9exiKoOizr.jpg",true),
  ("La Reine des neiges", "Anna, une jeune fille aussi audacieuse qu’optimiste, se lance dans un incroyable voyage en compagnie de Kristoff, un montagnard expérimenté, et de son fidèle renne, Sven à la recherche de sa sœur, Elsa, la Reine des Neiges qui a plongé le royaume d’Arendelle dans un hiver éternel… En chemin, ils vont rencontrer de mystérieux trolls et un drôle de bonhomme de neige nommé Olaf, braver les conditions extrêmes des sommets escarpés et glacés, et affronter la magie qui les guette à chaque pas.", "2013", "1:42:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/nnQLuzh2H6tSk1U0Zyu0ju16FXU.jpg", "https://www.youtube.com/embed/uyP70r9PS6A?si=L9kgMELin_1YeEdy", "Kristen Bell, Idina Menzel, Jonathan Groff, Josh Gad, Livvy Stubenrauch", "Walt Disney", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/cBeP4gkMmlPuCCZdTgCOPi1rUHZ.jpg",true),
  ("Raiponce", "Quand le bandit le plus recherché du royaume, Flynn Rider, se cache dans une mystérieuse tour, il est pris en otage par Raiponce, une jolie adolescente avec des cheveux de 20 mètres. La curieuse ravisseuse de Flynn, qui cherche à s’échapper de la tour où elle est enfermée depuis des années, conclut un accord avec le voleur et le duo improbable se lance dans une aventure pleine d’action, en compagnie du cheval Maximus, d'un camélon surprotecteur du nom de Pascal, et d'une bande de voyous.", "2010", "1:41:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/xZhAFR0N2r5q7tJNWaBGzHUaeb5.jpg", "https://www.youtube.com/embed/VYh2Y41uTcA?si=IX8SJv24V3jMgDOj", "Mandy Moore, Zachary Levi, Donna Murphy, Ron Perlman", "Walt Disney", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/cWczNud8Y8i8ab0Z4bxos4myWYO.jpg",true),
  ("My Hero Academia: You're Next", "Dans une société où les héros et les vilains s'affrontent continuellement au nom de la paix et du chaos, Deku, un étudiant du lycée U.A. qui aspire à devenir le meilleur héros possible, affronte celui qui imite le héros qu'il admire depuis longtemps. Deku et les autres élèves de la classe 1-A du lycée U.A. pourront-ils protéger le monde en mettant fin aux agissements de Dark Might, l'homme qui prétend être le nouveau symbole de la paix ?", "2024", "1:50:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/s7FB4JpSwAfr1DzFopB42u2zt3v.jpg", "https://www.youtube.com/embed/CDVU8JBdsfo?si=qocG2G5ml382md72", "Daiki Yamashita, Meru Nukumi, Mamoru Miyano, Kenta Miyake", "Tensai Okamura", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/hd1TvTUGjkoYoqvXYfSBpI5Ri9B.jpg",true),
  ("Notre histoire policière", "Ce documentaire qui navigue entre réalité et fiction se penche sur la corruption qui gangrène la police mexicaine grâce aux témoignages de deux agents.", "2021", "1:47:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fhvNCrsYEzebPhrCFuFNOsdtfxQ.jpg", "https://www.youtube.com/embed/xr3T32WXahY?si=UB8fTac39vhKXcNF", "Mónica del Carmen, Raúl Briones, María Teresa Hernández Cañas, Leonardo Alonso", "Alonso Ruizpalacios", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/uhTQG1X4dD0ItT4foUvaHvbhKhG.jpg",true),
  ("Police", "Virginie, Erik et Aristide, trois flics parisiens, se voient obligés d’accepter une mission inhabituelle : reconduire un étranger à la frontière. Sur le chemin de l’aéroport, Virginie comprend que leur prisonnier risque la mort s’il rentre dans son pays. Face à cet insoutenable cas de conscience, elle cherche à convaincre ses collègues de le laisser s’échapper.", "2020", "1:39:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/wPaZ1bREHJI4At9IdBHnXMbOsd7.jpg", "https://www.youtube.com/embed/CiLH5uy_j5k?si=_CerkETqDh-927Hf", "Omar Sy, Virginie Efira, Grégory Gadebois, Payman Maadi, Anne-Pascale Clairembourg", "Anne Fontaine", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/bInCRTfq1RvXGACQwls2LHOWPEm.jpg",true),
  ("Greedy People", "Les habitants éclectiques d'une petite ville insulaire pittoresque doivent naviguer dans un meurtre sensationnel et la découverte d'un million de dollars, conduisant à une série de décisions de plus en plus mauvaises qui bouleversent la communauté autrefois paisible.", "2024", "1:53:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qkmFPxiawqjGhxuC3HvN9sVuJbD.jpg", "https://www.youtube.com/embed/5U7RaN3pwHk?si=lwFK3T6Zb_wyvDYl", "Himesh Patel, Joseph Gordon-Levitt, Lily James, Uzo Aduba", "Potsy Ponciroli", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/5s2VqyV8AlFMZJrUIYKlzg7TNQN.jpg",true),
  ("High Rollers", "Mason, un maître voleur, vit une vie de rêve dans l'opulence aux côtés de son équipe et de sa petite amie Decker. Lorsque son ennemi juré Salazar kidnappe Decker, Mason doit tenter un braquage de casino à haut risque pour la sauver, tout en échappant aux rivaux de Salazar et au FBI.", "2025", "1:41:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/khRNFRUAmak8LcahJYmg5xNJy59.jpg", "https://www.youtube.com/embed/tVaU3af0j4I?si=Wi3W0Yb8NsCItXvW", "John Travolta, Gina Gershon, Lukas Haas, Quavo, Kelly Greyson", "Randall Emmett", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/me3SisKfnxwBP69aOVKAVMw9vDM.jpg",true),
  ("The Beekeeper", "La quête brutale de vengeance d’un homme prend des proportions démesurées alors que son passé d’agent secret d’une puissante organisation clandestine connue sous le nom des Apiculteurs est révélé.", "2024", "1:45:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/m7EOJS3Z7xRjZGhvvG7hF7JH1YX.jpg", "https://www.youtube.com/embed/QurMgKbwG3o?si=3dnh_Yg20bRjr0hc", "Jason Statham, Emmy Raver-Lampman, Josh Hutcherson, Bobby Naderi, Minnie Driver", "David Ayer", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",true),
  ("The Alto Knights", "Deux des plus redoutables figures de la mafia new-yorkaise, Frank Costello et Vito Genovese, luttent pour le contrôle de la ville. Autrefois meilleurs amis, la jalousie et les trahisons les mènent inévitablement à l’affrontement qui entraînera la chute de la mafia américaine.", "2025", "2:03:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/95KmR0xNuZZ6DNESDwLKWGIBvMg.jpg", "https://www.youtube.com/embed/dsaqPHZnLlA?si=7dV2KjqE8ewzOnNQ", "Robert De Niro, ebra Messing, Cosmo Jarvis, Kathrine Narducci, Michael Rispoli", "Warner bros", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/ePU3NGa52x7D13YYWszBpf8IOEn.jpg",true),
  ("A Murder in Oakland: Beauty is Deadly", "Recently cleared of an embezzlement charge, Detective Williams (Marcus D Spencer) is handed a high-profile murder case while also forced to take on a new partner. Williams is trying to solve this case while also working to see if he can trust his partner.", "2025", "1:13:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/iGz5PJNLHKZnWI2x36kP8igIZOe.jpg", "https://www.youtube.com/embed/sPiiL4PSVZ0?si=8nXy6Nd_JqjZ4aAZ", "Marcus D. Spencer, Chris Crofut, Michael J. Gwynn, Neil Bentley Fierro, Dawayne Jordan", "Marcus D. Spencer", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/iGz5PJNLHKZnWI2x36kP8igIZOe.jpg",true),
  ("Gunner", "Un vétéran des forces spéciales, Lee Gunner, emmène ses deux garçons faire du camping. Les garçons tombent sur un laboratoire de fentanyl et sont kidnappés par des trafiquants de drogue. Malheureusement pour ces derniers, Lee ne reculera devant rien pour ramener ses garçons sains et saufs.", "2024", "1:30:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cS2TXN1YlrCvkZmMxaevC1ZKtEz.jpg", "https://www.youtube.com/embed/0PEOojf2ghQ?si=PjGwMqPLWL4ygNcU", "Luke Hemsworth, Morgan Freeman, Joseph Baena, Maurice P. Kerry", "Warner Bros", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/bxwKC4qAbceMgHU1xCCTBK1eYdn.jpg",true),
  ("Strange Darling", "Un prédateur sans pitié traque une femme à travers la nature sauvage de l'Oregon. Faisant de son mieux pour déjouer son agresseur, elle s'affaiblit et perd peu à peu ses capacités. Face à un homme en mission, ce n'est qu'une question de temps avant que cette proie ne soit capturée.", "2024", "1:36:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gU9XCcNv2kzASnge3oFNtq1vFL.jpg", "https://www.youtube.com/embed/U5BXspdknH0?si=hatPmmLZ5-M1DKb1", "Willa Fitzgerald, Kyle Gallner, Madisen Beaty, Bianca A. Santos, Steven Michael Quezada", "JT Mollner", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/2ANHqBhbAhyIBRTLSVfENskpxon.jpg",true),
  ("Les graines du figuier sauvage", "Iman vient d’être promu juge d’instruction au tribunal révolutionnaire de Téhéran quand un immense mouvement de protestations populaires commence à secouer le pays. Dépassé par l’ampleur des évènements, il se confronte à l’absurdité d’un système et à ses injustices mais décide de s’y conformer. À la maison, ses deux filles, Rezvan et Sana, étudiantes, soutiennent le mouvement avec virulence, tandis que sa femme, Najmeh, tente de ménager les deux camps. La paranoïa envahit Iman lorsque son arme de service disparait mystérieusement…", "2024", "2:46:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YThe5RVeVVGm2gOkzykfXSElaO.jpg", "https://www.youtube.com/embed/hXKAmhlkMV8?si=Gc9I0cXcNOj3-qMN", "Misagh Zare, Soheila Golestani, Mahsa Rostami, Niousha Akhshi", "Mohammad Rasoulof", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/zqZzYVE4DWv92xrYSCEELPcLnUP.jpg",true),
  ("The Crow", "La veille de leur mariage, Eric Draven et Shelly Webster sont sauvagement assassinés. Un an plus tard, un corbeau ramène Eric à la vie au coeur d'une ville plongée dans les ténèbres. Eric va se laisser conduire là où sa vengeance l'appelle. Pour que justice soit faite. Pour l'amour de Shelly.", "2024", "1:51:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gEeLJ1F8SnLZk6q8PEAZ3qjWVdP.jpg", "https://www.youtube.com/embed/djSKp_pwmOA?si=XA7fnelL3LIH-fEb", "Bill Skarsgård, FKA twigs, Danny Huston, osette Simon, Laura Birn", "Rupert Sanders", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/503LUrI9juBk1rktOPzxyMUTDEu.jpg",true),
  ("Shang-Chi et la Légende des Dix Anneaux", "Shang-Chi va devoir affronter un passé qu’il pensait avoir laissé derrière lui lorsqu’il est pris dans la toile de la mystérieuse organisation des dix anneaux.", "2021", "2:11:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/g54eUtuCTAOQaNlVpr7Kpr7sVoH.jpg", "https://www.youtube.com/embed/YQOsxQUxMWk?si=wbC1hXs_ltW7bWL1", "Simu Liu, Tony Leung Chiu-Wai, Awkwafina, Ben Kingsley, Meng'er Zhang", "Marvel Studios", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/zxWAv1A34kdYslBi4ekMDtgIGUt.jpg",true),
  ("En fanfare", "Thibaut est un chef d’orchestre de renommée internationale qui parcourt le monde. Lorsqu’il apprend qu’il a été adopté, il découvre l’existence d’un frère, Jimmy, employé de cantine scolaire et qui joue du trombone dans une fanfare du nord de la France. En apparence tout les sépare, sauf l’amour de la musique. Détectant les capacités musicales exceptionnelles de son frère, Thibaut se donne pour mission de réparer l’injustice du destin. Jimmy se prend alors à rêver d’une autre vie…", "2024", "1:43:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5DD44mXSZSrgMRoLopr9LKcgF6N.jpg", "https://www.youtube.com/embed/KtscZL1eWmg?si=9LS6vJMN12mtxQKq", "Benjamin Lavernhe, Pierre Lottin, Sarah Suco, Clémence Massart-Weit, Ludmila Mikaël", "Emmanuel Courcol", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/fcKqExXt7tTNhNPFUJ2tHP5Ditx.jpg",true),
  ("Tár", "Lydia Tár, cheffe avant-gardiste d’un grand orchestre symphonique allemand, est au sommet de son art et de sa carrière. Le lancement de son livre approche et elle prépare un concerto très attendu de la célèbre Symphonie n° 5 de Gustav Mahler. Mais, en l’espace de quelques semaines, sa vie va se désagréger d’une façon singulièrement actuelle. En émerge un examen virulent des mécanismes du pouvoir, de leur impact et de leur persistance dans notre société.", "2022", "2:38:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vH1RnXfuz8n71xgF1t2xSRYYfe6.jpg", "https://www.youtube.com/embed/X1EgPoqvmO8?si=KH5kQLtO_pjLqazr", "Cate Blanchett, Nina Hoss, Noémie Merlant, Sophie Kauer, Julian Glover, Mark Strong", "Universal Pictures", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/fwhN9a0oRZvzc2tDuu5BZ59MOPz.jpg",true),
  ("Raya et le dernier dragon", "Il y a de cela fort longtemps, au royaume imaginaire de Kumandra, humains et dragons vivaient en harmonie. Mais un jour, une force maléfique s’abattit sur le royaume et les dragons se sacrifièrent pour sauver l’humanité. Lorsque cette force réapparaît cinq siècles plus tard, Raya, une guerrière solitaire, se met en quête du légendaire dernier dragon pour restaurer l’harmonie sur la terre de Kumandra, au sein d’un peuple désormais divisé. Commence pour elle un long voyage au cours duquel elle découvrira qu’il lui faudra bien plus qu’un dragon pour sauver le monde, et que la confiance et l’entraide seront essentiels pour conduire au succès cette périlleuse mission.", "2021", "1:47:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qDnumcHRzK9ljWtG5L1zRPhFRJg.jpg", "https://www.youtube.com/embed/g9w-kaayngA?si=RDwWNftfdzUsSusR", "Kelly Marie Tran, Awkwafina, Gemma Chan, Alan Tudyk", "Walt Disney", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/rcUcYzGGicDvhDs58uM44tJKB9F.jpg",true),
  ("Uri: The Surgical Strike", "Vihaan Singh Shergil de l’armée indienne par pour une mission qui marquera l’histoire de l’Inde en 2016.", "2019", "2:18:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/yNySAgpAnWmPpYinim9E0tUzJWG.jpg", "https://www.youtube.com/embed/Cg8sbRFS3zU?si=mTQ9-i3vA_cTurG7", "Vicky Kaushal, Paresh Rawal, Yami Gautam, Kirti Kulhari, Mohit Raina, Dhairya Karwa", "Aditya Dhar", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/gQLSOnXJmLDMZM8zfy4uw4mubo1.jpg",true),
  ("Sisu : De l'or et du sang ", "1944, en Laponie finlandaise, un ancien soldat reconverti en chercheur d'or trouve une grande quantité d'or. En essayant de rapporter son butin en ville, il devra se battre contre les forces nazies présentes en Finlande", "2022", "1:31:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/7U5ytZz3eInnBJaJUMFTdIqyZjj.jpg", "https://www.youtube.com/embed/qeU2R_hT_Zw?si=XyKBA2ycGvBaZEt8", "Jorma Tommila, Aksel Hennie, Jack Doolan, Mimosa Willamo, Onni Tommila", "Jalmari Helander", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/oGZhlVTBMZrHPuvGy8o6N4K8xGI.jpg",true),
  ("1917", "Pris dans la tourmente de la Première Guerre Mondiale, Schofield et Blake, deux jeunes soldats britanniques, se voient assigner une mission à proprement parler impossible. Porteurs d’un message qui pourrait empêcher une attaque dévastatrice et la mort de centaines de soldats, dont le frère de Blake, ils se lancent dans une véritable course contre la montre, derrière les lignes", "2019", "1:55:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/zppHKKEkHg9ZGzOdzZwW8lZYYqy.jpg", "https://www.youtube.com/embed/dcFdMwegkx0?si=ik2khjDGXAsR7ht9", "George MacKay, Dean-Charles Chapman, Mark Strong, Andrew Scott, Richard Madden", "Universal Pictures", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/tJgmraUAmVlJPlq72yC76tKDyC4.jpg",true), 
  ("Lee Miller", "L’incroyable vie de Lee Miller, ex-modèle pour Vogue et muse de Man Ray devenue l’une des premières femmes photographes de guerre. Partie sur le front et prête à tout pour témoigner des horreurs de la Seconde Guerre, elle a, par son courage et son refus des conventions, changé la façon de voir le monde.", "2024", "1:57:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/sDMERGnOuRqBtBSTH3p5XGtkrUn.jpg", "https://www.youtube.com/embed/cRZblc3DC7E?si=TqsSmXWCWp7qzeG9", "Kate Winslet, Andy Samberg, Alexander Skarsgård, Marion Cotillard, Andrea Riseborough", "Ellen Kuras", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/9SvSJJSgufM76vn9ddB0YMF6lzs.jpg",true),
  ("Sex", "Deux hommes hétérosexuels vivent des expériences qui les pousse à reconsidérer leur conception de la sexualité et du genre.", "2024", "2:05:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rTxYiujTHImHaEElz6ioRU7d4Z3.jpg", "https://www.youtube.com/embed/hKIgnML7kKA?si=cNeYD4s0afVGHpea", "Jan Gunnar Røise, Thorbjørn Harr, Birgitte Larsen, Nasrin Khusrawi", "Dag Johan Haugerud", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/mRP3qmD2JffBQqYRKOkbTZEI8VY.jpg",true),
  ("Hotel Desire", "Depuis la naissance de son petit garçon de huit ans, Antonia est une mère avant tout. Sa vie de femme est inexistante. Elle est divorcée et n'a plus eu d'homme dans sa vie. Elle travaille dans un hôtel, où elle écoute les conversations de ses collègues. Elle vit ainsi sa vie sexuelle par procuration. Antonia est déprimée. Mais aujourd'hui est un jour différent car elle va croiser un homme pas comme les autres...", "2011", "1:38:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/myzQj8Rk178DrWsiZjVKjz7Kj9P.jpg", "https://www.youtube.com/embed/QGJ-gBqcaHc?si=Jgd4d92IYP04izL6", "Saralisa Volm, Clemens Schick, Jan-Gregor Kremp, Herbert Knaup, Palina Rojinski", "Sergej Moya", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/z7ri7iqSlhfYYXMetCD8UzrQVu1.jpg",true),
  ("Room in Rome", "Deux étrangères, une Russe, une Espagnole, se rencontrent par hasard dans un hôtel de Rome. Elles ont une nuit pour faire connaissance...", "2010", "1:49:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gx2ENSap1D4nbjcz7cLLAs4S3fy.jpg", "https://www.youtube.com/embed/nOqhlfgj3hc?si=CifPnU3As-1agJOR", "Elena Anaya, Natasha Yarovenko, Enrico Lo Verso, Najwa Nimri", "Julio Medem", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/9Mbntsr7e27qwAqkiyDDQgqd7I9.jpg",true),
  ("After - Chapitre 1", "Depuis son plus jeune âge, Tessa était promise à un avenir tout tracé : une vie rangée, une brillante carrière, un mariage tranquille avec son fiancé de toujours. Jusqu’à sa rencontre avec Hardin à son arrivée à l’université. Grossier, provocateur, cruel, c’est le garçon le plus détestable qu’elle ait jamais croisé. Et pourtant, ce bad boy tatoué pourrait bien lui faire perdre tout contrôle…", "2019", "1:45:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qYDYA3jkSagHKjeKFmBPveBvGvn.jpg", "https://www.youtube.com/embed/5mYV2kL-Wn0?si=hR_wJIAaPJVBFKkO", "Josephine Langford, Hero Fiennes Tiffin, Shane Paul McGhie, Khadijha Red Thunder, Dylan Arnold", "Jenny Gage", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/997ToEZvF2Obp9zNZbY5ELVnmrW.jpg",true),
  ("Prison Break : The Joyce Mitchell Story", "L'histoire vraie de l'évasion et de la traque de Richard Matt et David Sweat, qui avaient réussi à s'enfuir de leur prison de l'état de New York avant d'être retrouvés 21 jours plus tard.", "2017", "1:43:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5oc1tiBRen3NCabw0q3iN5VWMXH.jpg","https://www.youtube.com/embed/w0wZDXrTmNg?si=oMJX9stgO8A_eVAJ", "Penelope Ann Miller, Myk Watford, Daniel Roebuck, Mike Ostroski, Joe Anderson", "Stephen Tolkin", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/wWG5yHv5gX4il6zjojHrNkmLY7u.jpg",true),
  ("Prison Break: The Final Break", "Quand le général Krantz, ancien chef de l'organisation défaite appelée Le Cartel est en prison avec T-Bag, et apprend que Sara Tancredi se retrouve derrière les barreaux, elle-aussi, pour meurtre, il saute sur l'occasion et projette de la tuer. Emprisonnée, elle estenceinte, et inquiète pour son bébé… Michael Scofield tentera de sauver Sara dans cette ultime trame qui conclut la série. Pour ce faire, il se fait aider par ses anciens complices et amis : Lincoln Burrows, Fernando Sucre et Alexander Mahone.", "2009", "1:29:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/jZRs7TEwsPnNMKGJs312uAg2lyo.jpg", "https://www.youtube.com/embed/MpnDkLGlhvk?si=0Z_ZWwGAqox7DTAP", "Wentworth Miller, Sarah Wayne Callies, Dominic Purcell, Jodi Lyn O'Keefe, Amaury Nolasco, Robert Knepper", "Kevin Hooks", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/4vwGAoDAOAUj2k0ELYopZzSUnPB.jpg",true), 
  ("Western", "Film américain réalisé par Bill Ross et Turner Ross.", "2015", "1:33:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fF0yZgBsy9pDo3OaUpbjcxLkH2c.jpg", "https://www.youtube.com/embed/YhCU2nu_G4k?si=UPJcAc-jnA84hPP-", "Bill Ross, Turner, Ross", "Open City Production", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/bS53UL2UGzgIMByB9lNBPI6LQVb.jpg",true),
  ("Lex Barker - De Tarzan au playboy de westerns", "Ce film retrace l'étonnante histoire de ce sex-symbol des écrans européens, qu'une carrière hollywoodienne ratée mena en Allemagne via l'Italie. Incarnation du héros protecteur volant au secours des plus faibles, Lex Barker s'impose, dans les années 1960, en ami américain plus vrai que nature, chevauchant, à renfort de grosses productions, à travers les plaines de la Yougoslavie non alignée. Si sa filmographie est aujourd'hui controversée pour son biais patriarcal et paternaliste, voire raciste, elle témoigne d'une époque où la conquête de l'Ouest, avec ses aventures et ses amitiés viriles, faisaient encore rêver l'Europe de la guerre froide.", "2023", "1:53:00","https://media.themoviedb.org/t/p/w600_and_h900_bestv2/flC36c9OVKBgpRy1biqQCMs2xsl.jpg", "https://www.youtube.com/embed/eOBYxwfFLMI?si=eVIL41acDwRv9TN7", "Lex Barker, Carmen G. Cervera, Karen Kondazian, Brett Halsey, Clemens Meyer", "Andreas G. Wagner", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/fJ852i2GmZgbqSUnMTWABqHSZIf.jpg",true),
  ("Horizon : Une saga américaine - Chapitre 1", "Chronique d'une période de 15 ans pendant la guerre de Sécession. L'expansion vers l'Ouest américain est semée d'embûches : les éléments naturels, les peuples indigènes qui vivent sur ces terres, et la détermination de ceux qui cherchent à les coloniser entraînent tout un pays dans une guerre contre lui-même.", "2024", "3:02:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/ioZl7IkWwImfMdHRXN5OD1cqTTj.jpg", "https://www.youtube.com/embed/EDKsKvpoASU?si=1ZFU_z8RxK7rnanW", "Kevin Costner, Sienna Miller, Sam Worthington, Jena Malone, Abbey Lee", "Warner Bros", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/8UOAYjhwSF3aPZhm6wgLuyHRyrR.jpg",true),
  ("Horizon : Une saga américaine - Chapitre 2", "La suite de l'histoire de la colonisation de l'Ouest américain. Elle suit les nouvelles aventures des personnages présentés pour la première fois dans Horizon : An American Saga.", "2024", "3:10:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2Ot7mpKYgqZfkGRaeV2kaHqKFkS.jpg", "https://www.youtube.com/embed/X5yOSu4R2ts?si=Kd8J9q8xvUTa7PX8", "Kevin Costner, Sienna Miller, Sam Worthington, Jena Malone, Abbey Lee", "Warner Bros", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/fdIxr2vzEypp0nC2bWiGg2jCLPl.jpg",true),
  ("Spaceman", "Un homme agoraphobe s'enferme dans un costume d'astronaute pour éviter les conséquences désastreuses de sa condition.", "2025", "1:32:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/tAtL6QZr0lMJD6fzbldn9xLWb3k.jpg", "https://www.youtube.com/embed/Mtr36Qc3K_w?si=XwX7xnoc1t8Wioaz", "Ryan Darcy, Isaac Cassidy, Elijah Cassidy", "Elijah Cassidy", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/ft8TTVYyS7bK2SshruuRCWDHh1T.jpg",true),
  ("Inside", "Mel est transféré d'un établissement pour mineurs à une prison pour adultes et se voit pris sous l'aile de Mark, le criminel le plus détesté d’Australie, et de Warren, un détenu bientôt libéré sous condition. Le triangle amoureux parental qui se forme entre eux devient leur perte.", "2025", "1:44:00", "https://media.themoviedb.org/t/p/w600_and_h900_bestv2/fNblwtRfaeIlLlM5kFrgUZYpE0a.jpg", "https://www.youtube.com/embed/ssvoAQELA3U?si=C2_YoUjsQUQjsVGs", "Guy Pearce, Vincent Miller, Cosmo Jarvis, Tammy Macintosh", "Charles Williams", "https://media.themoviedb.org/t/p/w1066_and_h600_bestv2/fCUMcvj9FzkiWJi3uyYiUPTlmKo.jpg",true); 


insert into user ( first_name, last_name, email, hashed_password, subscription, role)
VALUES
("Brayan", "Fagete", "adminod@gmail.com","$argon2id$v=19$m=19456,t=2,p=1$bu7ilozTjfTl0BIpGcpf+w$9EfzE01omfSwpvC7PGLuH/3mtmjQF1V7n5b8Yc4QoI0", 1, "administrateur"),
("Alex", "Taranne", "wild@gmail.com", "$argon2id$v=19$m=19456,t=2,p=1$bu7ilozTjfTl0BIpGcpf+w$9EfzE01omfSwpvC7PGLuH/3mtmjQF1V7n5b8Yc4QoI0", 0, "utilisateur" );
insert into genre (name)
VALUES
("Action"), ("Horreur"), ("Science-fiction"), ("Drame"), ("Romance"), ("Comédie"), ("Aventure"), ("Jeunesse"), ("Thriller"), ("Policier"), ("Criminel"), ("Fantastique"), ("Comédie musical"), ("Film d'animation"), ("Guerre"), ("Thriller érotique"), ("Prison"), ("Western");


insert into movie_genre (movie_id, genre_id)
VALUES
(1, 3),
(1, 1),
(2, 3),
(2, 9),
(3, 4),
(3, 11),
(4, 9),
(4, 10),
(4,17),
(4, 4),
(5, 1),
(5, 11),
(6, 9),
(7, 4),
(8, 3),
(9, 4),
(9, 18),
(10, 7),
(10, 4),
(10, 3),
(11, 4),
(12, 4),
(12, 5),
(13, 9),
(14, 4),
(15, 1),
(15, 3),
(15, 9),
(16, 7),
(16, 6),
(16, 8),
(16, 14),
(17, 6),
(17, 4),
(18, 9),
(18, 1),
(18, 10),
(19, 14),
(20, 4),
(21, 2),
(21, 9),
(21, 4),
(22, 16),
(23, 4),
(23, 9),
(24, 1),
(25, 6),
(25, 1),
(26, 2),
(27, 13),
(28, 4),
(29, 9),
(30, 2),
(30, 6),
(31, 3),
(32, 4),
(33, 2),
(33, 9),
(34, 4),
(34, 17),
(35, 6),
(35, 8),
(36, 9),
(36, 4),
(37, 7),
(37, 6),
(37, 8),
(37, 14),
(38, 4),
(39, 13),
(39, 4),
(40, 10),
(40, 4),
(40, 9),
(41, 4),
(42, 15),
(42, 4),
(43, 1),
(43, 3),
(44, 6),
(44, 5),
(45, 4),
(46, 9),
(46, 6),
(46, 4),
(47, 4),
(48, 2),
(48, 6),
(49, 2),
(49, 7),
(49, 9),
(49, 12),
(50, 12),
(51, 5),
(51, 16),
(52, 5),
(52, 6),
(53, 5),
(53, 7),
(54, 5),
(54, 13),
(55, 5),
(55, 16),
(56, 5),
(56, 2),
(56, 12),
(57, 5),
(57, 6),
(58, 7),
(58, 10),
(59, 7),
(59, 8),
(59, 15),
(60, 7),
(60, 18),
(60, 1),
(60, 5),
(61, 7),
(61, 1),
(61, 3),
(61, 12),
(62, 7),
(62, 1),
(62, 7),
(63, 7),
(63, 3),
(63, 1),
(63, 12),
(63, 8),
(64, 8),
(64, 14),
(64, 6),
(65, 8),
(65, 14),
(66, 8),
(66, 14),
(66, 13),
(67, 8),
(67, 13),
(67, 14),
(68, 8),
(68, 14),
(68, 7),
(69, 8),
(69, 14),
(69, 6),
(69, 1),
(70, 10),
(70, 1),
(70, 17),
(71, 10),
(71, 1),
(71, 11),
(71, 6),
(72, 10),
(72, 8),
(73, 10),
(73, 1),
(73, 11),
(74, 11),
(74, 1),
(74, 7),
(74, 8),
(74, 10),
(75, 11),
(75, 17),
(75, 10),
(76, 11),
(76, 1),
(76, 10),
(76, 7),
(77, 11),
(77, 1),
(77, 10),
(77, 17),
(78, 11),
(78, 5),
(78, 9),
(78, 2),
(79, 11),
(79, 10),
(79, 7),
(79, 17),
(80, 12),
(80, 8),
(80, 7),
(80, 3),
(81, 12),
(81, 14),
(81, 3),
(81, 8),
(82, 13),
(82, 6),
(82, 8),
(83, 13),
(83, 5),
(83, 9),
(84, 14),
(84, 1),
(84, 3),
(84, 7),
(84, 8),
(85, 15),
(85, 1),
(85, 5),
(85, 9),
(85, 17),
(86, 15),
(86, 1),
(86, 10),
(87, 15),
(87, 1),
(87, 7),
(87, 9),
(87, 17),
(88, 15),
(88, 1),
(88, 10),
(88, 11),
(89, 16),
(89, 5),
(89, 4),
(90, 16),
(90, 6),
(90, 7),
(90, 5),
(91, 5),
(91, 16),
(91, 7),
(91, 8),
(92, 16),
(92, 5),
(92, 7),
(93, 17),
(93, 11),
(93, 1),
(93, 9),
(94, 1),
(94, 8),
(94, 17),
(94, 11),
(94, 10),
(95, 1),
(95, 18),
(95, 7),
(95, 15),
(96, 18),
(96, 7),
(96, 11),
(97, 18),
(97, 1),
(97, 10),
(97, 8),
(98, 18),
(98, 1),
(98, 10),
(98, 8),
(99, 12),
(99, 1),
(99, 7),
(100, 18),
(100, 1);
